### ISSUE TITLE
Event propagation through Router.svelte

### ISSUE THREAD

**Issue by DEADF00D** [ykrods/svelte-spa-history-router#3]
Hey there !

**First thank you very much for this project, it improve a lot the features of svelte-spa-router, and perfectly match my needs.**

During my project developpement, I met the need of using `events` into a sub-component invoked by `Router.svelte`, that will be handled by the component that invoked the `<Router />` component.

Infortunatly events don't propagate after the `Router.svelte`.

I came with a small patch on `Router.svelte` like so:
```
<svelte:component this="{currentComponent}" {...currentProps} on:myEvent = { (e) => dispatch('myEvent', e.detail) } />
```

Maybe we could get a better solution that don't involve hard-coding the current project events ?
That would definitly improve `svelte-spa-history-router` usage.

Best regards.

**Comment by ykrods** [comment]
Thank you !

Event delegation has been discussed in following issue, but it seems to be not implemented yet.

https://github.com/sveltejs/svelte/issues/2837

So, I don't think there is a effective solution now.

**Comment by DEADF00D** [comment]
Yep,

Spoke about that on the Svelte discord yesterday.
And basically the only effectives solutions right now is through stores and override of the `dispatch` function of svelte, or by using custom event manager.

I will work on the first solution.
If it succeed, Would you accept a pull request about it ?

Best regards.

**Comment by ykrods** [comment]
If you submit a pull request, I will review it.

* If possible, please consider sending a PR or issue to svelte itself to make `on:*` available.
* Please provide a use case example when submitting pull request to us.

Good luck!

**Comment by ykrods** [comment]
Close this issue as `on:` is deprecated in svelte5 and event handlers can be passed in component properties. Thanks for raising this issue!
